name: Build and Release Weather CLI Tool

on:
  push:
    branches:
      - main  # Trigger the workflow on every push to main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use system-installed Python 3.9
        run: |
          python3.9 --version
          pip3.9 install --upgrade pip
          pip3.9 install requests pyinstaller

      - name: Build the project
        run: |
          pyinstaller --onefile weather.py

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: weather-tool
          path: dist/weather

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: weather-tool
          path: ./artifact

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(date +%Y.%m.%d-%H%M)  # Format: YYYY.MM.DD-HHMM
          gh release create "v$VERSION" ./artifact/weather \
            --title "Build v$VERSION" \
            --notes "Automated build and release for Weather CLI Tool."

