name: Build Weather CLI Tool

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  build:
    runs-on: self-hosted  # Use the self-hosted runner for the build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python 3.9
        run: |
          sudo dnf install -y python39 python39-pip  # Manually install Python 3.9 and pip on RHEL
          python3.9 -m pip install --upgrade pip  # Upgrade pip
          python3.9 -m pip install requests  # Install dependencies

      - name: Build the project
        run: |
          make build

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: weather-tool
          path: weather.py

  deploy:
    runs-on: self-hosted  # Ensure deployment happens on self-hosted runner
    needs: build  # Ensure the 'deploy' job runs only after the build job completes

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4  # Updated to v4
        with:
          name: weather-tool
          path: ./artifact

      - name: Deploy to remote server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          DESTINATION_FOLDER: /home/Result  # Path on the remote server where the file will be deployed
        run: |
          echo "Deploying binary to remote server..."
          
          # Create the SSH directory and add the private key
          mkdir -p ~/.ssh
          echo "$SERVER_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa  # Set permissions for the private key file
          
          # Add the server to known hosts to prevent SSH warnings
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          
          # Use SCP to copy the built binary to the remote server
          scp ./artifact/weather.py $SERVER_USER@$SERVER_IP:$DESTINATION_FOLDER

