name: Build and Release Weather CLI Tool

on:
  push:
    branches:
      - feature   # Trigger on push to the feature branch
      - dev       # Trigger on push to the dev branch
      - main      # Trigger on push to the main branch

env:
  BUILD_NUMBER: ${{ github.run_number }}  # Unique build number for this run
  BUILD_DIR: "dev-merger-build"           # Directory where dev builds will be stored

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use system-installed Python 3.9
        run: |
          python3.9 --version
          pip3.9 install --upgrade pip
          pip3.9 install requests pyinstaller

      - name: Build the project
        run: |
          pyinstaller --onefile weather.py
          ls -l dist  # List files in dist for debugging
          # Rename the output based on branch.
          if [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            mv dist/weather dist/weather-dev-${{ env.BUILD_NUMBER }}
          elif [ "${{ github.ref }}" = "refs/heads/main" ]; then
            mv dist/weather dist/weather-main-${{ env.BUILD_NUMBER }}
          else
            mv dist/weather dist/weather-${{ github.ref_name }}-${{ env.BUILD_NUMBER }}
          fi

      - name: Upload binary as artifact (for dev builds)
        if: github.ref == 'refs/heads/dev'
        uses: actions/upload-artifact@v4
        with:
          name: weather-tool-dev
          path: dist/weather-dev-${{ env.BUILD_NUMBER }}

  store_dev_build:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create folder for dev build
        run: |
          BUILD_NAME="weather-dev-${{ env.BUILD_NUMBER }}"
          mkdir -p $BUILD_DIR
          # Copy the dev build file into the folder
          cp dist/weather-dev-${{ env.BUILD_NUMBER }} $BUILD_DIR/$BUILD_NAME
          
      - name: Commit and push dev build to GitHub repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add $BUILD_DIR/
          git commit -m "Add build $BUILD_NAME"
          git push origin dev

  release:
    runs-on: ubuntu-latest
    needs: store_dev_build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download dev build artifact
        uses: actions/download-artifact@v4
        with:
          name: weather-tool-dev
          path: ./artifact

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="v${{ env.BUILD_NUMBER }}"  # Use build number for the release tag
          # Use the dev build file downloaded from artifact (note: its name is weather-dev-<BUILD_NUMBER>)
          gh release create "$VERSION" ./artifact/weather-dev-${{ env.BUILD_NUMBER }} \
            --title "Build $VERSION" \
            --notes "Automated build and release for Weather CLI Tool."

